# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "test.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ntest.proto\x12\x15\x63\x61i_lance.main.assert\x1a\x1bgoogle/protobuf/empty.proto"@\n\x0cWriteRequest\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x11\n\ttable_ipc\x18\x02 \x01(\x0c\x12\x0f\n\x07options\x18\x03 \x01(\t"\x1d\n\x0bReadRequest\x12\x0e\n\x06params\x18\x01 \x01(\t"!\n\x0cReadResponse\x12\x11\n\ttable_ipc\x18\x01 \x01(\x0c"\x11\n\x0fVersionsRequest")\n\x10VersionsResponse\x12\x15\n\rversions_json\x18\x01 \x01(\t""\n\x0fRollbackRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05""\n\x0fOptimizeRequest\x12\x0f\n\x07options\x18\x01 \x01(\t"/\n\x0cIndexRequest\x12\x0e\n\x06\x63olumn\x18\x01 \x01(\t\x12\x0f\n\x07options\x18\x02 \x01(\t"\x19\n\nSQLRequest\x12\x0b\n\x03sql\x18\x01 \x01(\t"1\n\x0bSQLResponse\x12\x11\n\tdata_json\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x03(\t2\xdb\x04\n\x0e\x44\x61tasetService\x12K\n\x0cWriteDataset\x12#.cai_lance.main.assert.WriteRequest\x1a\x16.google.protobuf.Empty\x12V\n\x0bReadDataset\x12".cai_lance.main.assert.ReadRequest\x1a#.cai_lance.main.assert.ReadResponse\x12_\n\x0cListVersions\x12&.cai_lance.main.assert.VersionsRequest\x1a\'.cai_lance.main.assert.VersionsResponse\x12Q\n\x0fRollbackDataset\x12&.cai_lance.main.assert.RollbackRequest\x1a\x16.google.protobuf.Empty\x12Q\n\x0fOptimizeDataset\x12&.cai_lance.main.assert.OptimizeRequest\x1a\x16.google.protobuf.Empty\x12J\n\x0b\x43reateIndex\x12#.cai_lance.main.assert.IndexRequest\x1a\x16.google.protobuf.Empty\x12Q\n\x08QuerySQL\x12!.cai_lance.main.assert.SQLRequest\x1a".cai_lance.main.assert.SQLResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "test_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WRITEREQUEST"]._serialized_start = 66
    _globals["_WRITEREQUEST"]._serialized_end = 130
    _globals["_READREQUEST"]._serialized_start = 132
    _globals["_READREQUEST"]._serialized_end = 161
    _globals["_READRESPONSE"]._serialized_start = 163
    _globals["_READRESPONSE"]._serialized_end = 196
    _globals["_VERSIONSREQUEST"]._serialized_start = 198
    _globals["_VERSIONSREQUEST"]._serialized_end = 215
    _globals["_VERSIONSRESPONSE"]._serialized_start = 217
    _globals["_VERSIONSRESPONSE"]._serialized_end = 258
    _globals["_ROLLBACKREQUEST"]._serialized_start = 260
    _globals["_ROLLBACKREQUEST"]._serialized_end = 294
    _globals["_OPTIMIZEREQUEST"]._serialized_start = 296
    _globals["_OPTIMIZEREQUEST"]._serialized_end = 330
    _globals["_INDEXREQUEST"]._serialized_start = 332
    _globals["_INDEXREQUEST"]._serialized_end = 379
    _globals["_SQLREQUEST"]._serialized_start = 381
    _globals["_SQLREQUEST"]._serialized_end = 406
    _globals["_SQLRESPONSE"]._serialized_start = 408
    _globals["_SQLRESPONSE"]._serialized_end = 457
    _globals["_DATASETSERVICE"]._serialized_start = 460
    _globals["_DATASETSERVICE"]._serialized_end = 1063
# @@protoc_insertion_point(module_scope)
